import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const code=readFileSync('site/public/boot.js','utf8');
function setup(saved,blocked=false){const classes=new Set(),timers=[],events={};let removed=false;const screen={classList:{add:v=>classes.add(v)},remove:()=>{removed=true}};const root={dataset:{},classList:{add:v=>classes.add(v),remove:v=>classes.delete(v)}};const window={addEventListener:(name,fn)=>events[name]=fn};const context={document:{documentElement:root,getElementById:()=>screen,fonts:{ready:Promise.resolve()}},window,localStorage:{getItem:()=>{if(blocked)throw Error('blocked');return saved}},matchMedia:()=>({matches:false}),setTimeout:(fn,ms)=>{const t={fn,ms};timers.push(t);return t},clearTimeout:t=>t.cleared=true,requestAnimationFrame:fn=>fn()};vm.runInNewContext(code,context);return{root,classes,timers,window,events,get removed(){return removed}}}
test('saved dark theme is set before app startup',()=>{const b=setup('dark');assert.equal(b.root.dataset.theme,'dark');assert.ok(b.classes.has('is-booting'))});
test('blocked storage still falls back to system theme and reveals on deadline',()=>{const b=setup(null,true);assert.equal(b.root.dataset.theme,'light');const deadline=b.timers.find(t=>t.ms===6500);assert.ok(deadline);deadline.fn();assert.ok(!b.classes.has('is-booting'));b.timers.find(t=>t.ms===220).fn();assert.ok(b.removed)});
test('ready UI waits for the catalogue and one animation cycle',async()=>{const b=setup('dark');let resolve;const ready=new Promise(r=>resolve=r);b.window.__waseFinishBoot(ready);b.timers.find(t=>t.ms===900).fn();await new Promise(r=>setImmediate(r));assert.ok(b.classes.has('is-booting'));resolve();await new Promise(r=>setImmediate(r));assert.ok(!b.classes.has('is-booting'));assert.ok(b.timers.find(t=>t.ms===6500).cleared)});
test('fast startup still shows a short animation',async()=>{const b=setup('light');b.window.__waseFinishBoot();await new Promise(r=>setImmediate(r));assert.ok(b.classes.has('is-booting'));b.timers.find(t=>t.ms===900).fn();await new Promise(r=>setImmediate(r));assert.ok(!b.classes.has('is-booting'))});
test('a failed catalogue cannot leave the loader stuck',async()=>{const b=setup('light');b.window.__waseFinishBoot(Promise.reject(Error('offline')));b.timers.find(t=>t.ms===900).fn();await new Promise(r=>setImmediate(r));assert.ok(!b.classes.has('is-booting'))});
test('back-forward cache restores the visible page',()=>{const b=setup('light');b.events.pageshow({persisted:true});assert.ok(!b.classes.has('is-booting'))});
