import { test,expect } from '@playwright/test';
import fs from 'node:fs';
async function fixture(page,type='image/png'){
 return Buffer.from(await page.evaluate(async(type)=>{const c=document.createElement('canvas');c.width=96;c.height=64;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,96,64);x.fillStyle='#f44937';x.fillRect(8,8,40,40);x.fillStyle='#222';x.beginPath();x.arc(64,34,19,0,Math.PI*2);x.fill();const b=await new Promise(r=>c.toBlob(r,type));return [...new Uint8Array(await b.arrayBuffer())];},type));
}
async function upload(page){await page.locator('#processing').selectOption('browser',{force:true});const png=await fixture(page);await page.locator('#file-input').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:png});await expect(page.locator('.file-row')).toHaveCount(1);await expect(page.locator('#convert')).toBeEnabled();}
async function target(page,name){await page.locator('#target .format-trigger').click();await page.locator(`#target [data-format="${name}"]`).click();}
async function output(page){await page.locator('#convert').click();await expect(page.locator('.file-row .download')).toBeVisible();const href=await page.locator('#file-list .download').getAttribute('href');return page.evaluate(async href=>{const b=await(await fetch(href)).blob();return {type:b.type,text:await b.text(),bytes:[...new Uint8Array(await b.arrayBuffer())]};},href);}
test('real vector paths, responsive main thread, no upload',async({page})=>{
 const errors=[],uploads=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')uploads.push(r.url());});await page.goto('/en/png-to-svg/');await upload(page);const out=await output(page);expect(out.type).toBe('image/svg+xml');expect(out.text).toContain('<path');expect(out.text).toContain('viewBox');expect(out.text).not.toContain('<image');expect(out.text).not.toContain('base64');expect(errors).toEqual([]);expect(uploads).toEqual([]);await expect(page.locator('body')).toBeVisible();
});
for(const fmt of ['PNG','JPG','WEBP','BMP','ICO'])test(`real ${fmt} bytes`,async({page})=>{
 await page.goto('/en/');await upload(page);await target(page,fmt);const out=await output(page),b=Buffer.from(out.bytes);expect(b.length).toBeGreaterThan(20);if(fmt==='PNG')expect([...b.subarray(0,4)]).toEqual([137,80,78,71]);if(fmt==='JPG')expect([...b.subarray(0,3)]).toEqual([255,216,255]);if(fmt==='WEBP'){expect(b.toString('ascii',0,4)).toBe('RIFF');expect(b.toString('ascii',8,12)).toBe('WEBP');}if(fmt==='BMP'){expect(b.toString('ascii',0,2)).toBe('BM');expect(b.readUInt32LE(18)).toBe(96);}if(fmt==='ICO'){expect(b.readUInt16LE(2)).toBe(1);expect(b.readUInt16LE(4)).toBe(1);expect([...b.subarray(22,26)]).toEqual([137,80,78,71]);}
});
test('SVG to PNG, malicious SVG rejected',async({page})=>{
 await page.goto('/ru/svg-to-png/');await page.locator('#processing').selectOption('browser',{force:true});await page.locator('#file-input').setInputFiles({name:'vector.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 30"><rect width="40" height="30" fill="red"/></svg>')});await expect(page.locator('.file-row')).toHaveCount(1);const out=await output(page);expect(out.type).toBe('image/png');await page.locator('#clear').click();await page.locator('#file-input').setInputFiles({name:'unsafe.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>')});await expect(page.locator('.announcement')).toContainText('SVG');await expect(page.locator('.file-row')).toHaveCount(0);
});
test('a local result previews the actual image and restores focus on close',async({page})=>{
 await page.goto('/en/');await upload(page);await target(page,'PNG');await output(page);
 const preview=page.locator('.file-row .preview-button');await preview.click();
 await expect(page.locator('.result-preview')).toBeVisible();
 const image=page.locator('.result-preview-content img');await expect(image).toBeVisible();
 await expect.poll(()=>image.evaluate(element=>element.complete&&element.naturalWidth>0)).toBe(true);
 await page.keyboard.press('Escape');await expect(page.locator('.result-preview')).not.toBeVisible();await expect(preview).toBeFocused();
});
test('image paste event and drag drop',async({page})=>{
 await page.goto('/en/');await page.locator('#processing').selectOption('browser',{force:true});const png=[...await fixture(page)];await page.evaluate(bytes=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'pasted.png',{type:'image/png'}));document.dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true}));},png);await expect(page.locator('.file-row')).toHaveCount(1);await page.locator('#clear').click();await page.evaluate(bytes=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'dropped.png',{type:'image/png'}));document.getElementById('dropzone').dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));},png);await expect(page.locator('.file-row')).toHaveCount(1);await output(page);
});
test('limits, invalid file, and repeated conversion',async({page})=>{
 await page.goto('/en/');await page.locator('#processing').selectOption('browser',{force:true});await page.locator('#file-input').setInputFiles({name:'not.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(page.locator('.announcement')).toContainText('unavailable in the current processing mode');await expect(page.locator('.file-row')).toHaveCount(0);const bomb=Buffer.alloc(24);bomb.set([137,80,78,71]);bomb.writeUInt32BE(20000,16);bomb.writeUInt32BE(20000,20);await page.locator('#file-input').setInputFiles({name:'huge.png',mimeType:'image/png',buffer:bomb});await expect(page.locator('.announcement')).toContainText('megapixel');await upload(page);await output(page);await target(page,'WEBP');await expect(page.locator('#file-list .download')).toHaveCount(0);expect((await output(page)).type).toBe('image/webp');
});
test('all locales, mobile overflow, theme, no tracking by default',async({page})=>{
 const tracking=[];page.on('request',r=>{if(/yandex|google-analytics/.test(r.url()))tracking.push(r.url());});for(const lang of ['en','ru','zh']){await page.goto('/'+lang+'/');await expect(page.locator('html')).toHaveAttribute('lang',lang==='zh'?'zh-CN':lang);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('#target .format-trigger').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator("#target .format-popover input").fill("PNG");await page.locator(`#target [data-format="PNG"]`).click();}await page.locator('.theme-choice summary').click();await page.locator('[data-theme-choice=dark]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');expect(tracking).toEqual([]);
});
test('SEO readable without JavaScript and true 404 on server design',async({browser})=>{
 const ctx=await browser.newContext({javaScriptEnabled:false});const page=await ctx.newPage();await page.goto('http://127.0.0.1:5188/ru/png-to-svg/');await expect(page.locator('h1')).toHaveText('Конвертер PNG в SVG');await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','https://wase.download/ru/png-to-svg/');await expect(page.locator('link[hreflang="zh-CN"]')).toHaveCount(1);await ctx.close();
});
test('gallery screenshots desktop and mobile',async({page},info)=>{
 await page.goto('/ru/png-to-svg/');await page.screenshot({path:`test-results/${info.project.name}-ru.png`,fullPage:true});await upload(page);await output(page);await page.locator('#workspace').scrollIntoViewIfNeeded();await page.screenshot({path:`test-results/${info.project.name}-converted.png`});
});
