test.skip(!process.env.RUN_SERVER_TESTS,'Run with RUN_SERVER_TESTS=1 and local API enabled');
import { test,expect } from '@playwright/test';
import fs from 'node:fs';
test('server: real vector result and queue inside the main tool',async({page})=>{await page.goto('/ru/');await expect(page.locator('#processing option[value=server]')).toBeEnabled();await page.locator('#processing').selectOption('server',{force:true});await page.locator('#file-input').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url))});await expect(page.locator('#converter .file-row')).toHaveCount(1);await page.locator('#convert').click();await expect(page.locator('.download')).toBeVisible({timeout:65000});const svg=await page.locator('.download').evaluate(async a=>await(await fetch(a.href)).text());expect(svg).toContain('<path');expect(svg).not.toContain('<image');expect(await page.locator('.download').evaluate(e=>e.closest('#converter')!==null)).toBe(true);});
test('server: corrupt file fails next to the file, retry remains available',async({page})=>{await page.goto('/en/');await expect(page.locator('#processing option[value=server]')).toBeEnabled();await page.locator('#processing').selectOption('server',{force:true});await page.locator('#file-input').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('broken')});await page.locator('#convert').click();await expect(page.locator('.is-error')).toContainText('Choose another',{timeout:65000});await expect(page.locator('#convert')).toBeEnabled();});
test('server: invalid pair and foreign origin rejected',async({request})=>{const r=await request.post('/api/convert?from=png&to=invalid',{data:'bad'});expect(r.status()).toBe(400);const cross=await request.post('/api/convert?from=png&to=svg',{data:'bad',headers:{Origin:'https://other.example'}});expect(cross.status()).toBe(403);});

test('server: office PDF and audio MP3 contain real format bytes',async({request})=>{const pdf=await request.post('/api/convert?from=txt&to=pdf',{data:Buffer.from('Wase Download document conversion')});expect(pdf.status()).toBe(200);expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-');const n=16000,wav=Buffer.alloc(44+n*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(n,24);wav.writeUInt32LE(n*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(n*2,40);const mp3=await request.post('/api/convert?from=wav&to=mp3',{data:wav});expect(mp3.status()).toBe(200);expect((await mp3.body()).subarray(0,3).toString()).toBe('ID3');});
test('server: multi-file image output is a complete ZIP',async({request})=>{const response=await request.post('/api/convert?from=png&to=dzi',{data:fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url))});expect(response.status()).toBe(200);expect(response.headers()['content-type']).toContain('application/zip');const {unzipSync}=await import('fflate');const files=unzipSync(await response.body());expect(Object.keys(files).some(x=>x.endsWith('.dzi'))).toBe(true);expect(Object.keys(files).some(x=>x.endsWith('.jpeg')||x.endsWith('.jpg'))).toBe(true);expect(Object.keys(files)).not.toContain('input.png');});

test('server: AVIF vectorization exports paths rather than embedded pixels',async({request})=>{const avif=await request.post('/api/convert?from=png&to=avif',{data:fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url))});expect(avif.status()).toBe(200);const svg=await request.post('/api/convert?from=avif&to=svg',{data:await avif.body()});expect(svg.status()).toBe(200);const text=(await svg.body()).toString();expect(text).toContain('<path');expect(text).not.toContain('<image');});
