test.skip(!process.env.RUN_SERVER_TESTS,'Run with RUN_SERVER_TESTS=1 and local API enabled');
import { test,expect } from '@playwright/test';
import fs from 'node:fs';
test('server: real vector result and queue inside the main tool',async({page})=>{await page.goto('/ru/');await expect.poll(()=>page.locator('#processing option[value=server]').evaluate(o=>!o.disabled)).toBe(true);await page.locator('#processing').selectOption('server',{force:true});await page.locator('#file-input').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url))});await expect(page.locator('#converter .file-row')).toHaveCount(1);await page.locator('#convert').click();await expect(page.locator('.download')).toBeVisible({timeout:65000});const downloaded=page.waitForEvent('download');await page.locator('.download').click();const svg=fs.readFileSync(await (await downloaded).path(),'utf8');expect(svg).toContain('<path');expect(svg).not.toContain('<image');expect(await page.locator('.download').evaluate(e=>e.closest('#converter')!==null)).toBe(true);});
test('server: corrupt file fails next to the file, retry remains available',async({page})=>{await page.goto('/en/');await expect.poll(()=>page.locator('#processing option[value=server]').evaluate(o=>!o.disabled)).toBe(true);await page.locator('#processing').selectOption('server',{force:true});await page.locator('#file-input').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('broken')});await page.locator('#convert').click();await expect(page.locator('.is-error')).toContainText('Choose another',{timeout:65000});await expect(page.locator('#convert')).toBeEnabled();});
test('server: invalid pair and foreign origin rejected',async({request})=>{const r=await request.post('/api/convert?from=png&to=invalid',{data:'bad'});expect(r.status()).toBe(400);const cross=await request.post('/api/convert?from=png&to=svg',{data:'bad',headers:{Origin:'https://other.example'}});expect(cross.status()).toBe(403);});

test('server: office PDF and audio MP3 contain real format bytes',async({request})=>{const pdf=await request.post('/api/convert?from=txt&to=pdf',{data:Buffer.from('Wase Download document conversion')});expect(pdf.status()).toBe(200);expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-');const n=16000,wav=Buffer.alloc(44+n*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(n,24);wav.writeUInt32LE(n*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(n*2,40);const mp3=await request.post('/api/convert?from=wav&to=mp3',{data:wav});expect(mp3.status()).toBe(200);expect((await mp3.body()).subarray(0,3).toString()).toBe('ID3');});
test('server: multi-file image output is a complete ZIP',async({request})=>{const response=await request.post('/api/convert?from=png&to=dzi',{data:fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url))});expect(response.status()).toBe(200);expect(response.headers()['content-type']).toContain('application/zip');const {unzipSync}=await import('fflate');const files=unzipSync(await response.body());expect(Object.keys(files).some(x=>x.endsWith('.dzi'))).toBe(true);expect(Object.keys(files).some(x=>x.endsWith('.jpeg')||x.endsWith('.jpg'))).toBe(true);expect(Object.keys(files)).not.toContain('input.png');});

test('server: AVIF vectorization exports paths rather than embedded pixels',async({request})=>{const avif=await request.post('/api/convert?from=png&to=avif',{data:fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url))});expect(avif.status()).toBe(200);const svg=await request.post('/api/convert?from=avif&to=svg',{data:await avif.body()});expect(svg.status()).toBe(200);const text=(await svg.body()).toString();expect(text).toContain('<path');expect(text).not.toContain('<image');});
test('server: HTML text, safe archive repack, real fonts and CAD',async({request})=>{const html=await request.post('/api/convert?from=html&to=txt',{data:Buffer.from('<html><body><h1>Wase Download</h1><p>Useful conversion.</p></body></html>')});expect(html.status()).toBe(200);expect((await html.body()).toString()).toContain('Useful conversion');const {zipSync,unzipSync}=await import('fflate');const zip=zipSync({'folder/a.txt':new TextEncoder().encode('hello')});const tar=await request.post('/api/convert?from=zip&to=tar.gz',{data:Buffer.from(zip)});expect(tar.status()).toBe(200);const back=await request.post('/api/convert?from=tar.gz&to=zip',{data:await tar.body()});expect(back.status()).toBe(200);expect(new TextDecoder().decode(unzipSync(await back.body())['folder/a.txt'])).toBe('hello');const malicious=await request.post('/api/convert?from=zip&to=tar',{data:Buffer.from(zipSync({'../escape.txt':new TextEncoder().encode('bad')}))});expect(malicious.status()).toBe(422);const font=fs.readFileSync(new URL('../site/public/fonts/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa25L7SUc.woff2',import.meta.url));const ttf=await request.post('/api/convert?from=woff2&to=ttf',{data:font});expect(ttf.status()).toBe(200);expect((await ttf.body()).subarray(0,4)).toEqual(Buffer.from([0,1,0,0]));const otf=await request.post('/api/convert?from=ttf&to=otf',{data:await ttf.body()});expect(otf.status()).toBe(200);expect((await otf.body()).subarray(0,4).toString()).toBe('OTTO');const obj=await request.post('/api/convert?from=obj&to=stl',{data:Buffer.from('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n')});expect(obj.status()).toBe(200);expect((await obj.body()).length).toBeGreaterThan(80);});
test('server: two visitors are queued without false busy errors',async({request})=>{const data=fs.readFileSync(new URL('./fixtures/logo.png',import.meta.url));const results=await Promise.all([request.post('/api/convert?from=png&to=svg',{data}),request.post('/api/convert?from=png&to=svg',{data})]);for(const result of results){expect(result.status()).toBe(200);expect((await result.body()).toString()).toContain('<path');}});

test('server: file dropped before catalogue response uses server conversion',async({page})=>{await page.route('**/api/formats',async route=>{await new Promise(r=>setTimeout(r,700));await route.continue();});await page.goto('/en/');await page.locator('#file-input').setInputFiles({name:'early.txt',mimeType:'text/plain',buffer:Buffer.from('Early upload')});await expect(page.locator('.file-row')).toHaveCount(1);await expect(page.locator('.file-meta')).toContainText('TXT');await page.locator('#target summary').click();await page.locator('#target input').fill('PDF');await page.locator('#target [data-format=PDF]').click();await page.locator('#convert').click();await expect(page.locator('.download')).toBeVisible({timeout:45000});const download=page.waitForEvent('download');await page.locator('.download').click();expect(fs.readFileSync(await(await download).path()).subarray(0,5).toString()).toBe('%PDF-');});

test('server: ebook and presentation round trips produce real outputs',async({request})=>{const html=Buffer.from('<html><head><title>Wase</title></head><body><h1>Wase</h1><p>A real presentation and book.</p></body></html>');const ebook=await request.post('/api/convert?from=html&to=epub',{data:html});expect(ebook.status()).toBe(200);const {unzipSync}=await import('fflate');expect(new TextDecoder().decode(unzipSync(await ebook.body()).mimetype)).toBe('application/epub+zip');const slides=await request.post('/api/convert?from=html&to=pptx',{data:html});expect(slides.status()).toBe(200);expect(Object.keys(unzipSync(await slides.body()))).toContain('ppt/presentation.xml');const pdf=await request.post('/api/convert?from=pptx&to=pdf',{data:await slides.body()});expect(pdf.status()).toBe(200);expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-');const odp=await request.post('/api/convert?from=pptx&to=odp',{data:await slides.body()});expect(odp.status()).toBe(200);expect(new TextDecoder().decode(unzipSync(await odp.body()).mimetype)).toBe('application/vnd.oasis.opendocument.presentation');});

test('server: video exports a real WebM container',async({request})=>{const video=await request.post('/api/convert?from=mp4&to=webm',{data:fs.readFileSync(new URL('./fixtures/short.mp4',import.meta.url))});expect(video.status()).toBe(200);expect((await video.body()).subarray(0,4)).toEqual(Buffer.from([0x1a,0x45,0xdf,0xa3]));});
