// SPDX-License-Identifier: MIT
// Small sequential fixtures, not a load test. Defaults to a local broker.
import {readFileSync,writeFileSync} from 'node:fs';import {zipSync,unzipSync} from 'fflate';
const origin=process.env.CONVERTER_TEST_ORIGIN||'http://127.0.0.1:5189',report=process.env.AUDIT_REPORT||'/tmp/wase-product-audit.json';
const text=s=>new TextEncoder().encode(s),zip=entries=>Buffer.from(zipSync(Object.fromEntries(Object.entries(entries).map(([n,s])=>[n,text(s)])),{level:0}));
const wav=Buffer.alloc(44+8000*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
const odp=zip({'mimetype':'application/vnd.oasis.opendocument.presentation','META-INF/manifest.xml':'<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.presentation"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>','content.xml':'<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" office:version="1.2"><office:body><office:presentation><draw:page draw:name="Slide1"><draw:frame svg:width="10cm" svg:height="3cm" svg:x="1cm" svg:y="1cm"><draw:text-box><text:p>Wase audit</text:p></draw:text-box></draw:frame></draw:page></office:presentation></office:body></office:document-content>'});
const epub=zip({'mimetype':'application/epub+zip','META-INF/container.xml':'<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="book.opf" media-type="application/oebps-package+xml"/></rootfiles></container>','book.opf':'<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">wase-audit</dc:identifier><dc:title>Wase audit</dc:title><dc:language>en</dc:language></metadata><manifest><item id="chapter" href="chapter.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="chapter"/></spine></package>','chapter.xhtml':'<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Audit</title></head><body><p>Wase audit</p></body></html>'});
const cases=[['image','png','svg',readFileSync('tests/fixtures/logo.png')],['vector','svg','png',text('<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><path fill="red" d="M1 1h50v50H1z"/></svg>')],['document','txt','pdf',text('Wase audit\nHello world')],['audio','wav','mp3',wav],['video','mp4','webm',readFileSync('tests/fixtures/short.mp4')],['archive','zip','tar.gz',zip({'hello.txt':'Wase audit'})],['font','woff2','woff',readFileSync('site/public/fonts/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7.woff2')],['cad','stl','obj',text('solid audit\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nvertex 0 1 0\nendloop\nendfacet\nendsolid audit')],['presentation','odp','pdf',odp],['ebook','epub','txt',epub]];
const results=[];
function valid(to,b){if(!b.length)return false;switch(to){case'svg':return b.toString().includes('<svg')&&b.toString().includes('<path');case'png':return b.subarray(1,4).toString()==='PNG';case'pdf':return b.subarray(0,5).toString()==='%PDF-';case'woff':return b.subarray(0,4).toString()==='wOFF';case'mp3':return b.subarray(0,3).toString()==='ID3'||b[0]===255;case'webm':return b.subarray(0,4).toString('hex')==='1a45dfa3';case'tar.gz':return b[0]===31&&b[1]===139;case'obj':return /(?:^|\n)v\s+[-\d.]/.test(b.toString());case'txt':return b.toString().includes('Wase audit');default:return false;}}
for(const [category,from,to,body] of cases){const start=Date.now();try{const r=await fetch(`${origin}/api/convert?from=${from}&to=${to}`,{method:'POST',body,headers:{'Content-Type':'application/octet-stream'},signal:AbortSignal.timeout(65000)});const bytes=Buffer.from(await r.arrayBuffer());let good=r.ok&&valid(to,bytes);if(r.ok&&r.headers.get('content-type')?.includes('application/zip'))good=Object.entries(unzipSync(bytes)).some(([name,data])=>name.toLowerCase().endsWith('.'+to)&&valid(to,Buffer.from(data)));results.push({category,from,to,http:r.status,bytes:bytes.length,passed:good,ms:Date.now()-start});}catch(e){results.push({category,from,to,passed:false,error:e.name,ms:Date.now()-start});}writeFileSync(report,JSON.stringify({origin,results},null,2));console.log(results.at(-1));}
for(const [scenario,from,to,headers,expected]of [
 ['unsupported-pair','3fr','mp4',{},400],
 ['forbidden-origin','png','svg',{Origin:'https://other.example'},403],
 ['empty-file','png','svg',{},422]
]){const r=await fetch(`${origin}/api/convert?from=${from}&to=${to}`,{method:'POST',body:scenario==='empty-file'?new Uint8Array():text('audit'),headers,signal:AbortSignal.timeout(15000)});await r.arrayBuffer();results.push({scenario,http:r.status,expected,passed:r.status===expected});writeFileSync(report,JSON.stringify({origin,results},null,2));console.log(results.at(-1));}
if(results.some(r=>!r.passed))process.exitCode=1;
