// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Wase Download contributors
import { mkdirSync,writeFileSync,readFileSync,rmSync } from 'node:fs';
import { blobatar } from 'blobatar/blob';
import { happy } from 'blobatar/expression';
import {publicCatalogue} from '../backend/conversion-policy.mjs';
import {pairs} from '../site/src/published-pairs.js';
import { strings,pairTitle } from '../site/src/strings.js';
import {categoryLabels,pairDescription,pairGuide} from '../site/src/seo.js';
import {formatRoutes} from '../site/src/format-routes.js';
const catalogue=publicCatalogue(JSON.parse(readFileSync('site/data/catalog.json','utf8')));
const base='https://wase.download';
export const inputRoutes=formatRoutes(catalogue);
const pairSlugs=Object.fromEntries(Object.entries(pairs).map(([slug,[a,b]])=>[a.toLowerCase()+':'+b.toLowerCase(),slug]));
const routeInputs=Object.fromEntries(Object.entries(inputRoutes).map(([input,path])=>[path,input]));
mkdirSync('site/public/mascots',{recursive:true});
for(const [i,hue] of [35,210,285,145].entries())writeFileSync(`site/public/mascots/helper-${i}.svg`,blobatar(`wase-helper-${i}`,{hue,background:false,tone:.62,expression:happy,traits:{shape:i===0?.86:i===1?.95:.72},title:'Wase helper'}));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {ArrowRight,Upload,Moon,ChevronDown,Clipboard,Check,Grid2X2} from 'lucide';
const icons={arrow:ArrowRight,upload:Upload,moon:Moon,chevron:ChevronDown,paste:Clipboard,check:Check,grid:Grid2X2};
const svg=name=>`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name].map(([tag,attrs])=>`<${tag} ${Object.entries(attrs).map(([k,v])=>`${k}="${esc(v)}"`).join(' ')}/>`).join('')}</svg>`;
const coffee={en:'Buy me a coffee',ru:'Купите мне кофе',zh:'请我喝杯咖啡'};
const pickerNames={en:{source:'Input format',target:'Output format',close:'Close',empty:'No matching formats'},ru:{source:'Исходный формат',target:'Новый формат',close:'Закрыть',empty:'Форматы не найдены'},zh:{source:'输入格式',target:'输出格式',close:'关闭',empty:'未找到格式'}};
function helper(i){const hues=[285,210,35,145],seeds=[2,1,0,3],markup=blobatar(`wase-helper-${seeds[i]}`,{hue:hues[i],background:false,tone:.62,traits:{shape:i===1?.95:.72}});return markup.replace(/<g fill="#(?:[0-9a-f]{6})">((?:(?!<\/g>)[\s\S])*?)<\/g>(<\/g>)?<\/svg>$/i,(_,eyes,outer='')=>`<g class="helper-gaze"><g class="helper-eyes" fill="#171624"><ellipse cx="37" cy="43" rx="7" ry="10" fill="#fff"/><ellipse cx="62" cy="43" rx="7" ry="10" fill="#fff"/><ellipse cx="38" cy="44" rx="3.8" ry="6.3"/><ellipse cx="63" cy="44" rx="3.8" ry="6.3"/></g></g><path class="helper-smile" d="M43 59q7 7 14 0" fill="none" stroke="#171624" stroke-width="2.5" stroke-linecap="round"/><g class="helper-spinner" fill="none" stroke="#171624" stroke-width="3"><circle cx="37" cy="46" r="5" stroke-dasharray="22 10"/><circle cx="62" cy="46" r="5" stroke-dasharray="22 10"/></g>${outer}</svg>`);}
function selector(t,id,value,formats){const lang=Object.keys(strings).find(key=>strings[key]===t)||'en';const labels=pickerNames[lang]||pickerNames.en;return `<div class="format-select" id="${id}"><button type="button" class="format-trigger" aria-haspopup="dialog" aria-controls="${id}-dialog" aria-expanded="false"><span class="format-value">${esc(value)}</span>${svg('chevron')}</button><dialog id="${id}-dialog" class="format-dialog" aria-labelledby="${id}-title"><div class="format-popover"><div class="picker-heading"><h2 id="${id}-title">${labels[id]}</h2><button type="button" class="picker-close" aria-label="${labels.close}">×</button></div><label class="search"><span class="sr-only">${t.search}</span><input type="search" placeholder="${t.search}" autocomplete="off"></label><div class="picker-body"><div class="category-list"></div><div class="picker-results"><div class="format-grid">${formats.map(f=>`<button type="button" data-format="${f}" aria-pressed="${f===value}">${esc(f)}</button>`).join('')}</div><p class="picker-empty" hidden>${labels.empty}</p></div></div></div></dialog></div>`}
function formatPage(lang,t){return `<main class="legal format-index"><h1>${t.formatsTitle}</h1><p>${t.formatsText}</p><h2>${t.tested}</h2><div class="conversion-links">${[...new Set(Object.values(pairs).map(p=>p[0]))].sort().map(source=>{const entries=Object.entries(pairs).filter(([,p])=>p[0]===source);return `<details class="format-group"><summary>${esc(source)}<span>${entries.length}</span></summary><div class="conversion-links">${entries.map(([slug,pair])=>`<a href="/${lang}/${slug}/">${pair.join(' → ')}</a>`).join('')}</div></details>`;}).join('')}</div><h2>${t.catalogue}</h2>${Object.entries(categoryLabels[lang]).map(([key,name])=>{const inputs=Object.keys(catalogue.inputs).filter(v=>catalogue.categories[v]===key).sort();return `<details class="format-group"><summary>${name}<span>${inputs.length}</span></summary><p>${inputs.map(v=>`<a href="/${lang}/${inputRoutes[v]}/">${esc(v.toUpperCase())}</a>`).join(' · ')}</p></details>`;}).join('')}<p>${t.limits}</p><a href="/formats.json">JSON →</a> · <a href="/${lang}/developers/">MCP →</a></main>`;}
export function page(lang,slug=''){
 const input=routeInputs[slug],outputs=input?catalogue.groups[catalogue.inputs[input]].filter(v=>v!==input):null;
 const defaultOutput=outputs&&(['png','pdf','txt','mp3','zip','stl'].find(v=>outputs.includes(v))||outputs[0]||input);
 const t=strings[lang],pair=input?[input.toUpperCase(),defaultOutput.toUpperCase()]:pairs[slug],kind=['privacy','about','formats','developers'].includes(slug)?slug:null;
 const title=input?({en:`${input.toUpperCase()} file converter`,ru:`Конвертер файлов ${input.toUpperCase()}`,zh:`${input.toUpperCase()} 文件转换器`})[lang]:kind?t[kind+'Title']:pair?pairTitle(lang,...pair):t.title;
 const description=input?({en:`Choose an output format for ${input.toUpperCase()}. ${outputs.length} directions declared by the installed engines. Availability depends on file contents; see tested conversions and limitations.`,ru:`Выберите выходной формат для ${input.toUpperCase()}. Движки заявляют ${outputs.length} направлений; возможность обработки зависит от содержимого файла. Смотрите проверенные конвертации и ограничения.`,zh:`为 ${input.toUpperCase()} 选择输出格式。已安装引擎声明 ${outputs.length} 个方向，能否处理取决于文件内容，请查看已测试的转换和限制。`})[lang]:pair?pairDescription(lang,...pair):kind?t[kind+'Text']:t.lead;
 const path=`/${lang}/${slug?slug+'/':''}`;
 const guide=pair?pairGuide(lang,...pair):null;
 const related=pair?Object.entries(pairs).filter(([other,p])=>other!==slug&&(p[0]===pair[0]||p[1]===pair[1]||p[0]===pair[1])).slice(0,6):[];
 const languages=Object.keys(strings).map(l=>`<a href="/${l}/${slug?slug+'/':''}" lang="${l}" ${l===lang?'aria-current="page"':''}>${strings[l].lang}</a>`).join('');
 const head=`<!doctype html><html lang="${lang==='zh'?'zh-CN':lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#faf9f6"><title>${esc(title)} · wase.download</title>${process.env.GOOGLE_SITE_VERIFICATION?`<meta name="google-site-verification" content="${esc(process.env.GOOGLE_SITE_VERIFICATION)}">`:""}${process.env.YANDEX_SITE_VERIFICATION?`<meta name="yandex-verification" content="${esc(process.env.YANDEX_SITE_VERIFICATION)}">`:""}<meta name="description" content="${esc(description)}">${input?'<meta name="robots" content="noindex,follow">':''}<link rel="canonical" href="${base+path}">${Object.keys(strings).map(l=>`<link rel="alternate" hreflang="${l==='zh'?'zh-CN':l}" href="${base}/${l}/${slug?slug+'/':''}">`).join('')}<link rel="alternate" hreflang="x-default" href="${base}/en/${slug?slug+'/':''}"><meta property="og:title" content="${esc(title)} · wase.download"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${base+path}"><meta property="og:image" content="${base}/social.png"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="stylesheet" href="/fonts/inter.css"><link rel="stylesheet" href="/src/style.css"><script src="/language.js"></script><script type="module" src="/src/app.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':kind?'WebPage':'WebApplication',name:`${title} · wase.download`,url:base+path,inLanguage:lang,applicationCategory:kind?undefined:'MultimediaApplication',operatingSystem:kind?undefined:'Web browser',offers:kind?undefined:{'@type':'Offer',price:'0',priceCurrency:'USD'}}).replace(/</g,'\\u003c')}</script></head>`;
 const header=`<body data-lang="${lang}" ${input?'data-catalogue="true"':''} data-source="${pair?.[0]||'AUTO'}" data-target="${pair?.[1]||'SVG'}"><header class="header"><a class="brand" href="/${lang}/" aria-label="wase.download"><span class="brand-symbol"><img src="/favicon.svg" alt="" width="30" height="30"></span><span class="brand-wordmark">wase<span class="brand-dot">.download</span></span></a><div class="header-actions"><a class="coffee-link" href="https://dalink.to/wase_download" target="_blank" rel="noopener noreferrer" aria-label="${coffee[lang]}" title="${coffee[lang]}"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 8h13v6a6 6 0 0 1-12 0V8zM17 8h1a3 3 0 0 1 0 6h-1M3 21h16M8 3v2M12 3v2"/></svg><span>${coffee[lang]}</span></a><details class="language"><summary>${lang==='zh'?'中文':lang.toUpperCase()}${svg('chevron')}</summary><div>${languages}</div></details><button class="icon-button" id="theme" type="button" aria-label="${t.theme}">${svg('moon')}</button></div></header>`;
 const footer=`<footer><a class="brand" href="/${lang}/"><span class="brand-wordmark">wase<span class="brand-dot">.download</span></span></a><p>${t.footer}</p><div><a href="/${lang}/formats/">${t.formatsTitle}</a><a href="/${lang}/privacy/">${t.privacy}</a><a href="/${lang}/about/">${t.aboutTitle}</a><a href="https://github.com/vlad1337vlad1337-droid/wase-download" target="_blank" rel="noopener">GitHub ↗</a><button id="analytics-settings" type="button" class="text-button" hidden>${t.analytics}</button></div><small>© ${new Date().getUTCFullYear()} wase.download · <a href="https://github.com/vlad1337vlad1337-droid/wase-download/blob/master/THIRD_PARTY_NOTICES.md" target="_blank" rel="noopener">${({en:'Open source credits',ru:'Авторы и лицензии',zh:'作者与许可'})[lang]}</a></small></footer><aside id="consent" class="consent" hidden><p>${t.consent}</p><button type="button" data-consent="yes">${t.accept}</button><button type="button" data-consent="no">${t.decline}</button></aside></body></html>`;
 if(kind==='formats')return head+header+formatPage(lang,t)+footer;
 if(kind==='developers')return head+header+`<main class="legal"><h1>${t.developersTitle}</h1><p>${t.developersText}</p><h2>MCP</h2><pre>https://wase.download/api/mcp</pre><p>list_formats · conversion_info</p><a href="/formats.json">JSON →</a><h2>HTTP</h2><pre>POST /api/convert?from=png&amp;to=svg
Content-Type: application/octet-stream</pre><p>${t.limits}</p><a href="/${lang}/formats/">${t.formatsTitle} →</a></main>`+footer;
 if(kind)return head+header+`<main class="legal"><a href="/${lang}/">← ${t.title}</a><h1>${title}</h1><p>${t[kind+'Text']}</p><a href="https://github.com/vlad1337vlad1337-droid/wase-download">GitHub →</a></main>`+footer;
 const formats=['SVG','PNG','JPG','WEBP','BMP','ICO'];
 return head+header+`<main><section class="hero"><h1>${title}</h1></section><div class="converter-shell" data-state="idle"><div class="helper-scene" aria-hidden="true">${[0,1,2,3].map(i=>`<div class="helper-figure helper-${i}">${helper(i)}</div>`).join('')}</div>
 <section id="converter" class="converter" aria-label="${t.title}"><div class="processing"><label>${t.mode}<select id="processing"><option value="browser">${t.browser}</option><option value="server" disabled>${t.server}</option></select></label><span class="loading-helper" aria-hidden="true">${blobatar('wase-helper-1',{hue:210,background:false,tone:.62})}</span><span id="processing-note">${t.local}</span></div><div class="converter-top"><div class="formats">${selector(t,'source',pair?.[0]||'AUTO',['AUTO','PNG','JPG','WEBP','GIF','BMP','SVG'])}<span class="format-arrow">${svg('arrow')}</span><span class="sr-only">${t.to}</span>${selector(t,'target',pair?.[1]||'SVG',formats)}</div></div><p id="announcement" class="announcement" role="status" aria-live="polite"></p><section id="workspace" class="workspace" hidden><div class="workspace-header"><h2 id="file-count"></h2><button id="clear" type="button" class="text-button">${t.clear}</button></div><div id="file-list" class="file-list"></div><details class="settings"><summary>${t.settings}${svg('chevron')}</summary><div class="settings-grid"><label id="detail-setting">${t.style}<select id="detail"><option value="balanced">${t.balanced}</option><option value="simple">${t.simple}</option><option value="detailed">${t.detailed}</option></select></label><label id="colors-setting">${t.colors}<select id="colors"><option>16</option><option selected>32</option><option>64</option></select></label><label id="quality-setting" hidden>${t.quality}<select id="quality"><option value="0.92">92%</option><option value="0.8">80%</option><option value="1">100%</option></select></label><label>${t.dimensions}<select id="edge"><option value="0">${t.original}</option><option value="2048">2048 px</option><option value="1024">1024 px</option><option value="512">512 px</option></select></label></div></details><p class="workspace-note" id="format-note">${t.notice}</p><div class="convert-actions"><p>${t.filesHint}</p><button id="cancel" class="secondary" type="button" hidden>${t.cancel}</button><button id="download-zip" class="secondary" type="button" hidden>${t.zip}</button><button id="convert" class="primary" type="button">${t.convert} ${svg('arrow')}</button></div></section><div id="dropzone" class="dropzone"><div class="upload-symbol">${svg('upload')}</div><button id="choose" type="button" class="primary">${t.choose} ${svg('arrow')}</button><div class="paste-row"><button id="paste" class="paste-button" type="button">${svg('paste')} ${t.paste}<kbd>⌘V / Ctrl V</kbd></button></div><small>${t.limit}</small><input id="file-input" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/bmp,image/svg+xml" multiple hidden></div><div class="converter-bottom"><span>${svg('check')}${t.saving}</span><button id="example" type="button">${t.try} ↗</button></div></section></div>

${input?`<details class="conversion-guide" open><summary>${t.formatsTitle}</summary><p>${esc(description)}</p><p>${esc(t.formatsText)}</p><p>${esc(guide.source)}</p><p>${esc(t.limits)}</p><div class="conversion-links">${outputs.map(output=>{const tested=pairSlugs[input+':'+output];return `<a href="/${lang}/${tested?tested:inputRoutes[input]}/${tested?'':'?to='+encodeURIComponent(output)+'#converter'}">${esc(input.toUpperCase())} → ${esc(output.toUpperCase())}</a>`;}).join('')}</div><a href="/${lang}/formats/">${t.catalogue} →</a></details>`:pair?`<details class="conversion-guide"><summary>${t.guide}</summary><h2>${guide.heading}</h2><ol>${guide.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><p>${esc(description)}</p><p>${esc(guide.source)}</p><p>${esc(guide.target)}</p><p>${t.limits}</p><h2>${guide.related}</h2><div class="conversion-links">${related.map(([other,p])=>`<a href="/${lang}/${other}/">${p.join(' → ')}</a>`).join('')}</div><a href="/${lang}/formats/">${t.formatsTitle} →</a></details>`:''}</main>`+footer;
}
// Locale folders contain generated files only. Remove obsolete routes before rebuilding.
if(process.argv[1]===new URL(import.meta.url).pathname){
for(const l of Object.keys(strings))rmSync(`site/${l}`,{recursive:true,force:true});
for(const l of Object.keys(strings))for(const slug of ['',...Object.keys(pairs).slice(0,33),'privacy','about','formats','developers']){
 const dir=`site/${l}/${slug}`;mkdirSync(dir,{recursive:true});writeFileSync(dir+'/index.html',page(l,slug));
}
writeFileSync('site/index.html',page('en'));
const urls=Object.keys(strings).flatMap(l=>['',...Object.keys(pairs),'privacy','about','formats','developers'].map(s=>`${base}/${l}/${s?s+'/':''}`));
writeFileSync('site/public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`  <url><loc>${u}</loc></url>`).join('\n')}\n</urlset>\n`);
writeFileSync('site/public/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${base}/sitemap.xml\n`);

writeFileSync('site/public/formats.json',JSON.stringify(catalogue));
writeFileSync('site/public/llms.txt',`# wase.download\n\nSelf-hosted file conversion. Public pages are static HTML.\n\n- [Formats](${base}/en/formats/): Declared capabilities and tested pages.\n- [Machine catalogue](${base}/formats.json): Input-dependent targets; declarations are not guarantees.\n- [Developers](${base}/en/developers/): HTTP upload API and read-only MCP.\n- [Privacy](${base}/en/privacy/): Files deleted after conversion.\n\nMCP: ${base}/api/mcp (list_formats, conversion_info). No remote URL fetching.\nLimits: 100 MB per file, 20 files per batch; conversion is queued and resource-limited.\n`);

}
